name : The Dereck
brand : The Dereck
description : Dereck Curry's blog and website
url : http://thedereck.github.com
email : thedereck@thedereck.com

favicon :
  enabled : true
  local :
    enabled : true
    filename : TheDereck.png
    type : png
  remote :
    enabled : false
    url : false
    type : false

alert : false
notice : false

brief_bio :
  enabled : true
  image :
    enabled : true
    url : http://www.gravatar.com/avatar/2f8947394b8acb62ed0f08df91055f27.png?s=200
  social_links :
    enabled : true
    follow_name : Dereck
    facebook : false
    github : https://github.com/thedereck
    googleplus : https://plus.google.com/109660251296662910676
    linkedin : http://www.linkedin.com/in/dereckcurry
    pinterest : false
    twitter : http://www.twitter.com/_TheDereck_

bootstrap:
  css : spacelab.bootstrap.min.css
  responsive :
    enabled : true
    css : bootstrap-responsive.min.css
  js :
    enabled : true
    src : bootstrap.min.js

jquery:
  enabled : true
  src : jquery-1.9.1.min.js

font_awesome :
  enabled : true
  css : font-awesome.min.css

rss :
  enabled : true
  managingeditor :
    enabled : true
    managingeditor : thedereck@thedereck.com
  webmaster :
    enabled : true
    webmaster : thedereck@thedereck.com
  ttl :
    enabled : true
    ttl : 1800
  image :
    enabled : true
    image : http://www.gravatar.com/avatar/2f8947394b8acb62ed0f08df91055f27.png?s=200
