name : The Dereck
brand : The Dereck
description : Dereck Curry's blog and website
url : http://thedereck.github.com
email : thedereck@thedereck.com

favicon :
  enabled : true
  local :
    enabled : true
    partial_url : /img/TheDereck.png
    type : png
  remote :
    enabled : false
    full_url : false
    type : false

alert : Sample site alert.
notice : Sample site notice.

sections:
  brief_bio :
    enabled : true
    image :
      enabled : true
      url : http://www.gravatar.com/avatar/2f8947394b8acb62ed0f08df91055f27.png?s=200
    content :
      enabled : true
    social_links :
      enabled : true
  social_links :
    enabled : true
  github_projects :
    enabled : true
  external_links :
    enabled : true
  archive :
    enabled : true
  categories :
    enabled : true
  tags :
    enabled : true

navbar :
  categories :
    enabled : true
  tags :
    enabled : true
  github_projects :
    enabled : true
  social_links :
    enabled : true
  external_links :
    enabled : true

social_links :
  follow_name : Dereck
  links :
    - link :
      enabled : false
      name : Facebook
      font_awesome_icon : icon-facebook
      url : false
    - link :
      enabled : true
      name : GitHub
      font_awesome_icon : icon-github-alt
      url : https://github.com/TheDereck
    - link :
      enabled : true
      name: Google+
      font_awesome_icon : icon-google-plus
      url : https://plus.google.com/109660251296662910676
    - link :
      enabled : true
      name : Linkedin
      font_awesome_icon : icon-linkedin
      url : http://www.linkedin.com/in/dereckcurry
    - link :
      enabled : false
      font_awesome_icon : icon-pinterest
      name : Pinterest
      url : false
    - link :
      enabled : true
      name : Twitter
      font_awesome_icon : icon-twitter
      url : http://www.twitter.com/_TheDereck_

github_projects :
  header : My GitHub Projects
  projects :
  - project :
    name : gh-pages-blog
    url : https://github.com/thedereck/gh-pages-blog

external_links :
  header : Links
  links :
    - link :
      name : Baking Kookys
      url : http://bakingkookys.com

bootstrap:
  css : spacelab.bootstrap.min.css
  responsive :
    enabled : true
    css : bootstrap-responsive.min.css
  js :
    enabled : true
    src : bootstrap.min.js

jquery:
  enabled : true
  src : jquery-1.9.1.min.js

font_awesome :
  enabled : true
  css : font-awesome.min.css

rss :
  enabled : true
  managingeditor :
    enabled : true
    managingeditor : thedereck@thedereck.com
  webmaster :
    enabled : true
    webmaster : thedereck@thedereck.com
  ttl :
    enabled : true
    ttl : 300
  image :
    enabled : true
    image : http://www.gravatar.com/avatar/2f8947394b8acb62ed0f08df91055f27.png?s=200

disqus :
  enabled : true
  shortname : TheDereck

analytics :
  enabled : true
  google_analytics :
    enabled : true
    tracking_id : UA-7954274-5