name: The Dereck
brand: Dereck Curry

alert: This is a sample site alert.
notice: false

bootstrap_css: spacelab.bootstrap.min.css
bootstrap_responsive_css: bootstrap-responsive.min.css
bootstrap_js: bootstrap.min.js
jquery_js: jquery-1.9.1.min.js