name : The Dereck
brand : The Dereck
description : Dereck Curry's blog and website
url : http://thedereck.github.com
email : thedereck@thedereck.com

favicon :
  enabled : true
  local :
    enabled : true
    partial_url : /img/TheDereck.png
    type : png
  remote :
    enabled : false
    full_url : false
    type : false

alert : false
notice : false

sections:
  brief_bio :
    enabled : true
    image :
      enabled : true
      url : http://www.gravatar.com/avatar/2f8947394b8acb62ed0f08df91055f27.png?s=200
    content :
      enabled : true
    social_links :
      enabled : true
  github_projects :
    enabled : true
  categories :
    enabled : true
  tags :
    enabled : true

navbar :
  categories :
    enabled : true
  tags :
    enabled : true

social_links :
  follow_name : Dereck
  facebook :
    enabled : false
    url : false
  github :
    enabled : true
    url : https://github.com/thedereck
  googleplus :
    enabled : true
    url : https://plus.google.com/109660251296662910676
  linkedin :
    enabled : true
    url : http://www.linkedin.com/in/dereckcurry
  pinterest :
    enabled : false
    url : false
  twitter :
    enabled : true
    url : http://www.twitter.com/_TheDereck_

github_projects :
  - project :
    name : gh-pages-blog
    url : https://github.com/thedereck/gh-pages-blog
  - project :
    name : gh-pages-blog
    url : https://github.com/thedereck/gh-pages-blog2

bootstrap:
  css : spacelab.bootstrap.min.css
  responsive :
    enabled : true
    css : bootstrap-responsive.min.css
  js :
    enabled : true
    src : bootstrap.min.js

jquery:
  enabled : true
  src : jquery-1.9.1.min.js

font_awesome :
  enabled : true
  css : font-awesome.min.css

rss :
  enabled : true
  managingeditor :
    enabled : true
    managingeditor : thedereck@thedereck.com
  webmaster :
    enabled : true
    webmaster : thedereck@thedereck.com
  ttl :
    enabled : true
    ttl : 300
  image :
    enabled : true
    image : http://www.gravatar.com/avatar/2f8947394b8acb62ed0f08df91055f27.png?s=200

analytics :
  enabled : true
  google_analytics :
    enabled : true
    tracking_id : UA-7954274-5