name: The Dereck
brand: The Dereck

brief_bio: He's a cool dude.

facebook_social_link: false
github_social_link: https://github.com/thedereck
googleplus_social_link: https://plus.google.com/109660251296662910676
linkedin_social_link: http://www.linkedin.com/in/dereckcurry
pinterest_social_link: false
twitter_social_link: false

alert: false
notice: false

bootstrap_css: spacelab.bootstrap.min.css
bootstrap_responsive_css: bootstrap-responsive.min.css
bootstrap_js: bootstrap.min.js
jquery_js: jquery-1.9.1.min.js
font_awesome_css: font-awesome.min.css