name: The Dereck
brand: The Dereck

facebook_social_link: false
github_social_link: false
googleplus_social_link: false
linkedin_social_link: www.linkedin.com/in/dereckcurry
pinterest_social_link: false
twitter_social_link: false

alert: false
notice: false

bootstrap_css: spacelab.bootstrap.min.css
bootstrap_responsive_css: bootstrap-responsive.min.css
bootstrap_js: bootstrap.min.js
jquery_js: jquery-1.9.1.min.js
font_awesome_css: font-awesome.min.css