name : The Dereck
brand : The Dereck
description : Dereck Curry's blog and website
url : http://thedereck.github.com
email : thedereck@thedereck.com

alert : false
notice : false

brief_bio :
  enabled : true
  follow_name : Dereck
  gravatar_image : http://www.gravatar.com/avatar/2f8947394b8acb62ed0f08df91055f27.png?s=200
  social_links :
    enabled : true
    facebook_social_link : false
    github_social_link : https://github.com/thedereck
    googleplus_social_link : https://plus.google.com/109660251296662910676
    linkedin_social_link : http://www.linkedin.com/in/dereckcurry
    pinterest_social_link : false
    twitter_social_link : http://www.twitter.com/_TheDereck_

bootstrap_css : spacelab.bootstrap.min.css
bootstrap_responsive_css : bootstrap-responsive.min.css
bootstrap_js : bootstrap.min.js
jquery_js : jquery-1.9.1.min.js
font_awesome_css : font-awesome.min.css

rss_enabled : true
